# Generated by Django 6.1 on 2026-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=20, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('favorite_operator', models.CharField(max_length=50, verbose_name='喜爱干员')),
            ],
            options={
                'verbose_name': '反馈信息',
                'verbose_name_plural': '反馈信息',
                'db_table': 'contact',
            },
        ),
    ]
